"""
Reparse Burrow corpus attestations from cached raw_html.

Why this script exists
----------------------
``burrow_corpus.json`` is the ground truth: it holds the raw HTML fetched
from DSAL for every DED entry. The attestation lists in that file were
generated by whichever version of BurrowEntryParser was active at scrape
time. When the parser is improved (e.g. Pattern E added to recover language
markers hidden inside outer <b> blocks opened by grammatical qualifiers like
*fem.*, *pl.*, etc.), the attestations in ``burrow_corpus.json`` become
stale — but the raw HTML is still correct.

This script re-runs the *current* BurrowEntryParser against every entry's
``raw_html``, replaces ``attestations`` in place, then applies the same
gloss-repair pass used by ``repair_burrow_corpus_glosses.py``. The result is
written to ``burrow_corpus.cleaned.json``. No network I/O occurs.

Relation to the other scripts in this directory
-----------------------------------------------
- ``burrow_corpus_scraper.py``
      Fetches raw HTML from DSAL and calls the parser once per entry.
      Do not re-run this unless you need fresh HTML from the network.

- ``repair_burrow_corpus_glosses.py``
      Patches gloss *text* for entries that already exist in the corpus.
      It cannot add attestations that the parser originally missed.

- ``reparse_burrow_corpus.py``  (this file)
      Re-parses cached HTML with the current parser, then runs the same
      gloss-repair logic. Use this whenever the parser changes.

Usage
-----
From the repository root::

    python src/dravidian/scripts/cross-validating-dded-starling/reparse_burrow_corpus.py \\
        data/dravidian/burrow_ded/burrow_corpus.json \\
        --output data/dravidian/burrow_ded/burrow_corpus.cleaned.json
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from dataclasses import asdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# Sibling modules in the same directory.
from burrow_entry_parser import BurrowEntryParser
from repair_burrow_corpus_glosses import repair_corpus


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _lang_abbrevs(attestations: List[Dict[str, Any]]) -> set[str]:
    """Return the set of language abbreviations in an attestation list."""
    return {
        a.get("language_abbrev", "")
        for a in attestations
        if isinstance(a, dict) and a.get("language_abbrev")
    }


# ---------------------------------------------------------------------------
# Per-entry reparse
# ---------------------------------------------------------------------------


def _reparse_entry(
    entry: Dict[str, Any],
    parser: BurrowEntryParser,
) -> Tuple[List[Dict[str, Any]], bool]:
    """
    Re-parse one corpus entry's ``raw_html`` with the current parser.

    Parameters
    ----------
    entry:
        A single dict from ``corpus["entries"]``.
    parser:
        Shared BurrowEntryParser instance (stateless; safe to reuse).

    Returns
    -------
    (new_attestations, changed)
        ``new_attestations`` is the list of attestation dicts to store.
        ``changed`` is True when the set of language abbreviations or the
        total attestation count differs from what was previously stored.
        Callers use this flag to build the diff report without re-comparing
        every field.
    """
    raw_html: str = entry.get("raw_html", "")
    if not raw_html:
        # Entry was stored without HTML (shouldn't happen in a complete scrape,
        # but guard defensively so one bad entry doesn't abort the whole run).
        return entry.get("attestations", []), False

    # Use ded_number_raw (always a plain integer string like "72") rather than
    # ded_number ("App.72" for Appendix entries). parse_language_sections uses
    # this to locate the matching <number> tag inside the hw_result div.
    ded_number: Optional[str] = entry.get("ded_number_raw") or entry.get("ded_number")

    parsed = parser.parse_language_sections(raw_html, ded_number)
    new_attestations = [asdict(att) for att in parsed]

    old_langs = _lang_abbrevs(entry.get("attestations", []))
    new_langs = _lang_abbrevs(new_attestations)

    changed = (new_langs != old_langs) or (
        len(new_attestations) != len(entry.get("attestations", []))
    )

    return new_attestations, changed


# ---------------------------------------------------------------------------
# Full-corpus reparse
# ---------------------------------------------------------------------------


def reparse_corpus(
    data: Dict[str, Any],
) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """
    Re-parse all entries in the corpus.

    Iterates over ``data["entries"]``, calls ``_reparse_entry`` for each,
    and replaces ``entry["attestations"]`` with the freshly parsed result.
    All other fields (``raw_html``, ``full_text``, ``page``, ``edition``,
    ``ded_number``, etc.) are left untouched.

    Parameters
    ----------
    data:
        The loaded ``burrow_corpus.json`` dict.

    Returns
    -------
    (updated_data, diff_report)
        ``updated_data`` is the same dict with ``attestations`` replaced.
        ``diff_report`` is a structured summary of what changed, embedded
        into ``_reparse_meta`` in the output file for audit purposes.
    """
    parser = BurrowEntryParser()
    entries: List[Dict[str, Any]] = data.get("entries", [])

    changed_entries: List[Dict[str, Any]] = []
    skipped_no_html: int = 0

    for i, entry in enumerate(entries):
        if not entry.get("raw_html"):
            skipped_no_html += 1
            continue

        new_attestations, changed = _reparse_entry(entry, parser)

        if changed:
            old_langs = _lang_abbrevs(entry.get("attestations", []))
            new_langs = _lang_abbrevs(new_attestations)

            changed_entries.append(
                {
                    "ded_number": entry.get("ded_number", f"index-{i}"),
                    "old_count": len(entry.get("attestations", [])),
                    "new_count": len(new_attestations),
                    # Gained/lost are the most actionable signal in the diff:
                    # "gained" confirms that a parser fix recovered a real language,
                    # "lost" is a regression warning that warrants manual review.
                    "gained": sorted(new_langs - old_langs),
                    "lost": sorted(old_langs - new_langs),
                }
            )

        entry["attestations"] = new_attestations

    diff_report = {
        "total_entries": len(entries),
        "entries_changed": len(changed_entries),
        "entries_skipped_no_html": skipped_no_html,
        "changes": changed_entries,
    }

    return data, diff_report


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _print_diff(diff: Dict[str, Any]) -> None:
    """Pretty-print the reparse diff report to stdout."""
    print(f"  Entries processed   : {diff['total_entries']}")
    print(f"  Entries changed     : {diff['entries_changed']}")
    if diff["entries_skipped_no_html"]:
        print(f"  Skipped (no html)   : {diff['entries_skipped_no_html']}")

    if not diff["changes"]:
        return

    print("\n  Changed entries:")
    for ch in diff["changes"]:
        gains = f"  +{ch['gained']}" if ch["gained"] else ""
        losses = f"  -{ch['lost']}" if ch["lost"] else ""
        print(
            f"    DED {ch['ded_number']:>8}:  "
            f"{ch['old_count']} -> {ch['new_count']} attestations"
            f"{gains}{losses}"
        )


def main() -> None:
    # Language abbreviations contain diacritics (e.g. "Koḍ.", "Manḍ.").
    # On Windows the default console codec (cp1252) cannot encode these, so
    # force UTF-8 output before any print() calls.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    arg_parser = argparse.ArgumentParser(
        description=(
            "Re-parse Burrow corpus attestations from cached raw_html, "
            "then apply gloss repairs. No network I/O required."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Example (from repository root):\n"
            "  python src/dravidian/scripts/cross-validating-dded-starling/"
            "reparse_burrow_corpus.py \\\n"
            "      data/dravidian/burrow_ded/burrow_corpus.json \\\n"
            "      --output data/dravidian/burrow_ded/burrow_corpus.cleaned.json"
        ),
    )
    arg_parser.add_argument(
        "corpus",
        help="Path to burrow_corpus.json (the raw scraped corpus, source of truth)",
    )
    arg_parser.add_argument(
        "--output",
        help=(
            "Output path for the cleaned corpus. "
            "Defaults to burrow_corpus.cleaned.json in the same directory as the input."
        ),
    )
    args = arg_parser.parse_args()

    in_path = Path(args.corpus)
    if not in_path.exists():
        print(f"Error: input file not found: {in_path}", file=sys.stderr)
        sys.exit(1)

    out_path = (
        Path(args.output)
        if args.output
        else in_path.parent / "burrow_corpus.cleaned.json"
    )

    print(f"Input  : {in_path}")
    print(f"Output : {out_path}")

    # ------------------------------------------------------------------ #
    # Load
    # ------------------------------------------------------------------ #
    print("\nLoading corpus...")
    with in_path.open("r", encoding="utf-8-sig") as f:
        data = json.load(f)
    print(f"  {len(data.get('entries', []))} entries loaded.")

    # ------------------------------------------------------------------ #
    # Step 1: Re-parse
    # Re-run BurrowEntryParser on each entry's raw_html. This is the step
    # that repair_burrow_corpus_glosses.py cannot perform — it populates
    # attestations[] from scratch rather than patching existing glosses.
    # ------------------------------------------------------------------ #
    print("\nStep 1/2 — Re-parsing attestations from raw_html ...")
    t0 = time.perf_counter()
    data, diff = reparse_corpus(data)
    elapsed = time.perf_counter() - t0
    print(f"  Done in {elapsed:.1f}s.")
    _print_diff(diff)

    # ------------------------------------------------------------------ #
    # Step 2: Gloss repair
    # Fixes spacing artifacts and resolves "id." (idem) glosses by
    # substituting the preceding attestation's gloss text. Delegates to
    # repair_burrow_corpus_glosses.repair_corpus to avoid duplicating logic.
    # ------------------------------------------------------------------ #
    print("\nStep 2/2 — Repairing glosses ...")
    data = repair_corpus(data)
    repair_meta = data.get("_repair_meta", {})
    print(
        f"  {repair_meta.get('repaired_attestations', 0)} / "
        f"{repair_meta.get('total_attestations', 0)} attestation glosses repaired."
    )

    # ------------------------------------------------------------------ #
    # Embed audit metadata so future readers know exactly how the cleaned
    # corpus was built and which entries changed relative to the raw scrape.
    # ------------------------------------------------------------------ #
    data["_reparse_meta"] = {
        "script": "reparse_burrow_corpus.py",
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "source": str(in_path),
        "entries_processed": diff["total_entries"],
        "entries_changed": diff["entries_changed"],
        # Full change list kept here so a `git diff` on the JSON file shows
        # exactly which DED numbers gained or lost language attestations.
        "changes": diff["changes"],
    }

    # ------------------------------------------------------------------ #
    # Write
    # ------------------------------------------------------------------ #
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8-sig") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"\nWrote : {out_path}")


if __name__ == "__main__":
    main()
